import { createContext, useContext, useState } from 'react';

const translations = {
  EN: {
    home: 'Home',
    stories: 'Stories',
    simulator: 'Simulator',
    lms: 'Courses',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    dashboard: 'Dashboard',
    admin: 'Admin',
    profile: 'Profile',
    welcome: 'Welcome to Ubuntu Mathematics',
    tagline: 'Learn mathematics through African innovation stories',
    exploreStories: 'Explore Stories',
    startLearning: 'Start Learning',
    myProgress: 'My Progress',
    badges: 'Badges',
    courses: 'Courses',
    subscribe: 'Subscribe',
    pricing: 'Pricing',
    email: 'Email',
    password: 'Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    loading: 'Loading...',
    error: 'Something went wrong',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    create: 'Create',
    publish: 'Publish',
    draft: 'Draft',
    search: 'Search',
    filter: 'Filter',
    all: 'All',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    free: 'Free',
    basic: 'Basic',
    professional: 'Professional',
    institutional: 'Institutional',
    monthly: 'Monthly',
    annual: 'Annual',
    perMonth: '/month',
    perYear: '/year',
    enroll: 'Enroll Now',
    enrolled: 'Enrolled',
    continue: 'Continue',
    complete: 'Complete',
    certificate: 'Certificate',
    download: 'Download',
    progress: 'Progress',
    completed: 'Completed',
    lessons: 'Lessons',
    duration: 'Duration',
    instructor: 'Instructor',
    level: 'Level',
    category: 'Category',
    tags: 'Tags',
    description: 'Description',
    title: 'Title',
    region: 'Region',
    location: 'Location',
    innovators: 'Innovators',
    readTime: 'Read Time',
    watchVideo: 'Watch Video',
    startJourney: 'Start Journey',
    exploreLogic: 'Explore Logic',
    solveProblems: 'Solve Problems',
    earnBadge: 'Earn Badge',
    phase1: 'Phase 1: Story',
    phase2: 'Phase 2: Innovation',
    phase3: 'Phase 3: Math Module',
    correct: 'Correct!',
    incorrect: 'Incorrect',
    tryAgain: 'Try Again',
    next: 'Next',
    previous: 'Previous',
    submit: 'Submit',
    score: 'Score',
    timeSpent: 'Time Spent',
    totalUsers: 'Total Users',
    totalBadges: 'Total Badges',
    conversionRate: 'Conversion Rate',
    completionRate: 'Completion Rate',
    avgTime: 'Avg. Time',
    recentActivity: 'Recent Activity',
    users: 'Users',
    role: 'Role',
    student: 'Student',
    name: 'Name',
    actions: 'Actions',
    importFromGoogle: 'Import from Google Classroom',
    connectGoogle: 'Connect Google Account',
    selectCourses: 'Select Courses to Import',
    import: 'Import',
    minutes: 'min',
    ubuntuFormula: 'Ubuntu Formula',
    difficultyLevel: 'Difficulty Level',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    badgeReward: 'Badge Reward',
    problemSet: 'Problem Set',
    question: 'Question',
    answer: 'Answer',
    explanation: 'Explanation',
    simulator: 'Ubuntu Value Simulator',
    communitySize: 'Community Size',
    resourcesCaptured: 'Resources Captured',
    innovationType: 'Innovation Type',
    modelType: 'Model Type',
    ubuntu: 'Ubuntu',
    traditional: 'Traditional',
    calculate: 'Calculate',
    socialDividend: 'Social Dividend',
    strategicReserves: 'Strategic Reserves',
    communalValue: 'Communal Value Score',
    payNow: 'Pay Now',
    selectPlan: 'Select Plan',
    currentPlan: 'Current Plan',
    upgrade: 'Upgrade',
    cancelSubscription: 'Cancel Subscription',
    paymentSuccess: 'Payment Successful!',
    paymentFailed: 'Payment Failed',
    subscriptionActive: 'Subscription Active',
  },
  FR: {
    home: 'Accueil',
    stories: 'Histoires',
    simulator: 'Simulateur',
    lms: 'Cours',
    login: 'Connexion',
    register: "S'inscrire",
    logout: 'Déconnexion',
    dashboard: 'Tableau de bord',
    admin: 'Admin',
    profile: 'Profil',
    welcome: 'Bienvenue sur Ubuntu Mathématiques',
    tagline: "Apprenez les mathématiques à travers des histoires d'innovation africaine",
    exploreStories: 'Explorer les histoires',
    startLearning: 'Commencer à apprendre',
    loading: 'Chargement...',
    error: "Quelque chose s'est mal passé",
    signIn: 'Se connecter',
    signUp: "S'inscrire",
    email: 'Email',
    password: 'Mot de passe',
    firstName: 'Prénom',
    lastName: 'Nom',
    enroll: "S'inscrire",
    enrolled: 'Inscrit',
    continue: 'Continuer',
    complete: 'Terminer',
    certificate: 'Certificat',
    progress: 'Progrès',
    completed: 'Terminé',
    lessons: 'Leçons',
    calculate: 'Calculer',
    submit: 'Soumettre',
    next: 'Suivant',
    previous: 'Précédent',
    correct: 'Correct!',
    incorrect: 'Incorrect',
    tryAgain: 'Réessayer',
    save: 'Sauvegarder',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    create: 'Créer',
    search: 'Rechercher',
    payNow: 'Payer maintenant',
    monthly: 'Mensuel',
    annual: 'Annuel',
  },
  SW: {
    home: 'Nyumbani',
    stories: 'Hadithi',
    simulator: 'Kisimulizi',
    lms: 'Kozi',
    login: 'Ingia',
    register: 'Jisajili',
    logout: 'Toka',
    dashboard: 'Dashibodi',
    admin: 'Msimamizi',
    profile: 'Wasifu',
    welcome: 'Karibu Ubuntu Hisabati',
    tagline: 'Jifunze hisabati kupitia hadithi za uvumbuzi wa Afrika',
    exploreStories: 'Chunguza Hadithi',
    startLearning: 'Anza Kujifunza',
    loading: 'Inapakia...',
    error: 'Kuna hitilafu',
    signIn: 'Ingia',
    signUp: 'Jisajili',
    email: 'Barua pepe',
    password: 'Nywila',
    firstName: 'Jina la kwanza',
    lastName: 'Jina la familia',
    enroll: 'Jiandikishe',
    enrolled: 'Ameandikishwa',
    continue: 'Endelea',
    complete: 'Maliza',
    certificate: 'Cheti',
    progress: 'Maendeleo',
    completed: 'Imekamilika',
    lessons: 'Masomo',
    calculate: 'Hesabu',
    submit: 'Wasilisha',
    next: 'Ifuatayo',
    previous: 'Iliyotangulia',
    correct: 'Sahihi!',
    incorrect: 'Sivyo',
    tryAgain: 'Jaribu tena',
    save: 'Hifadhi',
    cancel: 'Ghairi',
    delete: 'Futa',
    edit: 'Hariri',
    create: 'Unda',
    search: 'Tafuta',
    payNow: 'Lipa sasa',
    monthly: 'Kila mwezi',
    annual: 'Kila mwaka',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('EN');

  const t = (key) => translations[lang]?.[key] ?? translations.EN[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languages: ['EN', 'FR', 'SW'] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
